/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutenticadaRouteImport } from './routes/_autenticada'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AutenticadaAppRouteImport } from './routes/_autenticada/app'
import { Route as AutenticadaAuditoriaRouteImport } from './routes/_autenticada/auditoria'
import { Route as AutenticadaDesignVersionsRouteImport } from './routes/_autenticada/design-versions'
import { Route as AutenticadaDisposicionRouteImport } from './routes/_autenticada/disposicion'
import { Route as AutenticadaEvidenciaRouteImport } from './routes/_autenticada/evidencia'
import { Route as AutenticadaExportacionRouteImport } from './routes/_autenticada/exportacion'
import { Route as AutenticadaImportacionRouteImport } from './routes/_autenticada/importacion'
import { Route as AutenticadaInsightsRouteImport } from './routes/_autenticada/insights'
import { Route as AutenticadaJourneysRouteImport } from './routes/_autenticada/journeys'
import { Route as AutenticadaPersonasRouteImport } from './routes/_autenticada/personas'
import { Route as AutenticadaPropuestasRouteImport } from './routes/_autenticada/propuestas'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as AutenticadaDesignVersionDesignVersionIdRouteImport } from './routes/_autenticada/design-version.$designVersionId'
import { Route as AutenticadaJourneyJourneyIdRouteImport } from './routes/_autenticada/journey.$journeyId'
import { Route as AutenticadaProyectoProyectoIdRouteImport } from './routes/_autenticada/proyecto.$proyectoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadaRoute = AutenticadaRouteImport.update({
  id: '/_autenticada',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadaAppRoute = AutenticadaAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaAuditoriaRoute = AutenticadaAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaDesignVersionsRoute =
  AutenticadaDesignVersionsRouteImport.update({
    id: '/design-versions',
    path: '/design-versions',
    getParentRoute: () => AutenticadaRoute,
  } as any)
const AutenticadaDisposicionRoute = AutenticadaDisposicionRouteImport.update({
  id: '/disposicion',
  path: '/disposicion',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaEvidenciaRoute = AutenticadaEvidenciaRouteImport.update({
  id: '/evidencia',
  path: '/evidencia',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaExportacionRoute = AutenticadaExportacionRouteImport.update({
  id: '/exportacion',
  path: '/exportacion',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaImportacionRoute = AutenticadaImportacionRouteImport.update({
  id: '/importacion',
  path: '/importacion',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaInsightsRoute = AutenticadaInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaJourneysRoute = AutenticadaJourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaPersonasRoute = AutenticadaPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaPropuestasRoute = AutenticadaPropuestasRouteImport.update({
  id: '/propuestas',
  path: '/propuestas',
  getParentRoute: () => AutenticadaRoute,
} as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadaDesignVersionDesignVersionIdRoute =
  AutenticadaDesignVersionDesignVersionIdRouteImport.update({
    id: '/design-version/$designVersionId',
    path: '/design-version/$designVersionId',
    getParentRoute: () => AutenticadaRoute,
  } as any)
const AutenticadaJourneyJourneyIdRoute =
  AutenticadaJourneyJourneyIdRouteImport.update({
    id: '/journey/$journeyId',
    path: '/journey/$journeyId',
    getParentRoute: () => AutenticadaRoute,
  } as any)
const AutenticadaProyectoProyectoIdRoute =
  AutenticadaProyectoProyectoIdRouteImport.update({
    id: '/proyecto/$proyectoId',
    path: '/proyecto/$proyectoId',
    getParentRoute: () => AutenticadaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AutenticadaAppRoute
  '/auditoria': typeof AutenticadaAuditoriaRoute
  '/design-versions': typeof AutenticadaDesignVersionsRoute
  '/disposicion': typeof AutenticadaDisposicionRoute
  '/evidencia': typeof AutenticadaEvidenciaRoute
  '/exportacion': typeof AutenticadaExportacionRoute
  '/importacion': typeof AutenticadaImportacionRoute
  '/insights': typeof AutenticadaInsightsRoute
  '/journeys': typeof AutenticadaJourneysRoute
  '/personas': typeof AutenticadaPersonasRoute
  '/propuestas': typeof AutenticadaPropuestasRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/design-version/$designVersionId': typeof AutenticadaDesignVersionDesignVersionIdRoute
  '/journey/$journeyId': typeof AutenticadaJourneyJourneyIdRoute
  '/proyecto/$proyectoId': typeof AutenticadaProyectoProyectoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AutenticadaAppRoute
  '/auditoria': typeof AutenticadaAuditoriaRoute
  '/design-versions': typeof AutenticadaDesignVersionsRoute
  '/disposicion': typeof AutenticadaDisposicionRoute
  '/evidencia': typeof AutenticadaEvidenciaRoute
  '/exportacion': typeof AutenticadaExportacionRoute
  '/importacion': typeof AutenticadaImportacionRoute
  '/insights': typeof AutenticadaInsightsRoute
  '/journeys': typeof AutenticadaJourneysRoute
  '/personas': typeof AutenticadaPersonasRoute
  '/propuestas': typeof AutenticadaPropuestasRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/design-version/$designVersionId': typeof AutenticadaDesignVersionDesignVersionIdRoute
  '/journey/$journeyId': typeof AutenticadaJourneyJourneyIdRoute
  '/proyecto/$proyectoId': typeof AutenticadaProyectoProyectoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_autenticada': typeof AutenticadaRouteWithChildren
  '/login': typeof LoginRoute
  '/_autenticada/app': typeof AutenticadaAppRoute
  '/_autenticada/auditoria': typeof AutenticadaAuditoriaRoute
  '/_autenticada/design-versions': typeof AutenticadaDesignVersionsRoute
  '/_autenticada/disposicion': typeof AutenticadaDisposicionRoute
  '/_autenticada/evidencia': typeof AutenticadaEvidenciaRoute
  '/_autenticada/exportacion': typeof AutenticadaExportacionRoute
  '/_autenticada/importacion': typeof AutenticadaImportacionRoute
  '/_autenticada/insights': typeof AutenticadaInsightsRoute
  '/_autenticada/journeys': typeof AutenticadaJourneysRoute
  '/_autenticada/personas': typeof AutenticadaPersonasRoute
  '/_autenticada/propuestas': typeof AutenticadaPropuestasRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/_autenticada/design-version/$designVersionId': typeof AutenticadaDesignVersionDesignVersionIdRoute
  '/_autenticada/journey/$journeyId': typeof AutenticadaJourneyJourneyIdRoute
  '/_autenticada/proyecto/$proyectoId': typeof AutenticadaProyectoProyectoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/auditoria'
    | '/design-versions'
    | '/disposicion'
    | '/evidencia'
    | '/exportacion'
    | '/importacion'
    | '/insights'
    | '/journeys'
    | '/personas'
    | '/propuestas'
    | '/invitacion/$token'
    | '/design-version/$designVersionId'
    | '/journey/$journeyId'
    | '/proyecto/$proyectoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/auditoria'
    | '/design-versions'
    | '/disposicion'
    | '/evidencia'
    | '/exportacion'
    | '/importacion'
    | '/insights'
    | '/journeys'
    | '/personas'
    | '/propuestas'
    | '/invitacion/$token'
    | '/design-version/$designVersionId'
    | '/journey/$journeyId'
    | '/proyecto/$proyectoId'
  id:
    | '__root__'
    | '/'
    | '/_autenticada'
    | '/login'
    | '/_autenticada/app'
    | '/_autenticada/auditoria'
    | '/_autenticada/design-versions'
    | '/_autenticada/disposicion'
    | '/_autenticada/evidencia'
    | '/_autenticada/exportacion'
    | '/_autenticada/importacion'
    | '/_autenticada/insights'
    | '/_autenticada/journeys'
    | '/_autenticada/personas'
    | '/_autenticada/propuestas'
    | '/invitacion/$token'
    | '/_autenticada/design-version/$designVersionId'
    | '/_autenticada/journey/$journeyId'
    | '/_autenticada/proyecto/$proyectoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutenticadaRoute: typeof AutenticadaRouteWithChildren
  LoginRoute: typeof LoginRoute
  InvitacionTokenRoute: typeof InvitacionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticada': {
      id: '/_autenticada'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AutenticadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticada/app': {
      id: '/_autenticada/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AutenticadaAppRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/auditoria': {
      id: '/_autenticada/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AutenticadaAuditoriaRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/design-versions': {
      id: '/_autenticada/design-versions'
      path: '/design-versions'
      fullPath: '/design-versions'
      preLoaderRoute: typeof AutenticadaDesignVersionsRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/disposicion': {
      id: '/_autenticada/disposicion'
      path: '/disposicion'
      fullPath: '/disposicion'
      preLoaderRoute: typeof AutenticadaDisposicionRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/evidencia': {
      id: '/_autenticada/evidencia'
      path: '/evidencia'
      fullPath: '/evidencia'
      preLoaderRoute: typeof AutenticadaEvidenciaRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/exportacion': {
      id: '/_autenticada/exportacion'
      path: '/exportacion'
      fullPath: '/exportacion'
      preLoaderRoute: typeof AutenticadaExportacionRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/importacion': {
      id: '/_autenticada/importacion'
      path: '/importacion'
      fullPath: '/importacion'
      preLoaderRoute: typeof AutenticadaImportacionRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/insights': {
      id: '/_autenticada/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AutenticadaInsightsRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/journeys': {
      id: '/_autenticada/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof AutenticadaJourneysRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/personas': {
      id: '/_autenticada/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AutenticadaPersonasRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/propuestas': {
      id: '/_autenticada/propuestas'
      path: '/propuestas'
      fullPath: '/propuestas'
      preLoaderRoute: typeof AutenticadaPropuestasRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticada/design-version/$designVersionId': {
      id: '/_autenticada/design-version/$designVersionId'
      path: '/design-version/$designVersionId'
      fullPath: '/design-version/$designVersionId'
      preLoaderRoute: typeof AutenticadaDesignVersionDesignVersionIdRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/journey/$journeyId': {
      id: '/_autenticada/journey/$journeyId'
      path: '/journey/$journeyId'
      fullPath: '/journey/$journeyId'
      preLoaderRoute: typeof AutenticadaJourneyJourneyIdRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/proyecto/$proyectoId': {
      id: '/_autenticada/proyecto/$proyectoId'
      path: '/proyecto/$proyectoId'
      fullPath: '/proyecto/$proyectoId'
      preLoaderRoute: typeof AutenticadaProyectoProyectoIdRouteImport
      parentRoute: typeof AutenticadaRoute
    }
  }
}

interface AutenticadaRouteChildren {
  AutenticadaAppRoute: typeof AutenticadaAppRoute
  AutenticadaAuditoriaRoute: typeof AutenticadaAuditoriaRoute
  AutenticadaDesignVersionsRoute: typeof AutenticadaDesignVersionsRoute
  AutenticadaDisposicionRoute: typeof AutenticadaDisposicionRoute
  AutenticadaEvidenciaRoute: typeof AutenticadaEvidenciaRoute
  AutenticadaExportacionRoute: typeof AutenticadaExportacionRoute
  AutenticadaImportacionRoute: typeof AutenticadaImportacionRoute
  AutenticadaInsightsRoute: typeof AutenticadaInsightsRoute
  AutenticadaJourneysRoute: typeof AutenticadaJourneysRoute
  AutenticadaPersonasRoute: typeof AutenticadaPersonasRoute
  AutenticadaPropuestasRoute: typeof AutenticadaPropuestasRoute
  AutenticadaDesignVersionDesignVersionIdRoute: typeof AutenticadaDesignVersionDesignVersionIdRoute
  AutenticadaJourneyJourneyIdRoute: typeof AutenticadaJourneyJourneyIdRoute
  AutenticadaProyectoProyectoIdRoute: typeof AutenticadaProyectoProyectoIdRoute
}

const AutenticadaRouteChildren: AutenticadaRouteChildren = {
  AutenticadaAppRoute: AutenticadaAppRoute,
  AutenticadaAuditoriaRoute: AutenticadaAuditoriaRoute,
  AutenticadaDesignVersionsRoute: AutenticadaDesignVersionsRoute,
  AutenticadaDisposicionRoute: AutenticadaDisposicionRoute,
  AutenticadaEvidenciaRoute: AutenticadaEvidenciaRoute,
  AutenticadaExportacionRoute: AutenticadaExportacionRoute,
  AutenticadaImportacionRoute: AutenticadaImportacionRoute,
  AutenticadaInsightsRoute: AutenticadaInsightsRoute,
  AutenticadaJourneysRoute: AutenticadaJourneysRoute,
  AutenticadaPersonasRoute: AutenticadaPersonasRoute,
  AutenticadaPropuestasRoute: AutenticadaPropuestasRoute,
  AutenticadaDesignVersionDesignVersionIdRoute:
    AutenticadaDesignVersionDesignVersionIdRoute,
  AutenticadaJourneyJourneyIdRoute: AutenticadaJourneyJourneyIdRoute,
  AutenticadaProyectoProyectoIdRoute: AutenticadaProyectoProyectoIdRoute,
}

const AutenticadaRouteWithChildren = AutenticadaRoute._addFileChildren(
  AutenticadaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutenticadaRoute: AutenticadaRouteWithChildren,
  LoginRoute: LoginRoute,
  InvitacionTokenRoute: InvitacionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
