/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutenticadaRouteImport } from './routes/_autenticada'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AutenticadaAppRouteImport } from './routes/_autenticada/app'
import { Route as AutenticadaAuditoriaRouteImport } from './routes/_autenticada/auditoria'
import { Route as AutenticadaImportacionRouteImport } from './routes/_autenticada/importacion'
import { Route as AutenticadaPersonasRouteImport } from './routes/_autenticada/personas'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as AutenticadaProyectoProyectoIdRouteImport } from './routes/_autenticada/proyecto.$proyectoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadaRoute = AutenticadaRouteImport.update({
  id: '/_autenticada',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadaAppRoute = AutenticadaAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaAuditoriaRoute = AutenticadaAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaImportacionRoute = AutenticadaImportacionRouteImport.update({
  id: '/importacion',
  path: '/importacion',
  getParentRoute: () => AutenticadaRoute,
} as any)
const AutenticadaPersonasRoute = AutenticadaPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AutenticadaRoute,
} as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadaProyectoProyectoIdRoute =
  AutenticadaProyectoProyectoIdRouteImport.update({
    id: '/proyecto/$proyectoId',
    path: '/proyecto/$proyectoId',
    getParentRoute: () => AutenticadaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AutenticadaAppRoute
  '/auditoria': typeof AutenticadaAuditoriaRoute
  '/importacion': typeof AutenticadaImportacionRoute
  '/personas': typeof AutenticadaPersonasRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/proyecto/$proyectoId': typeof AutenticadaProyectoProyectoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AutenticadaAppRoute
  '/auditoria': typeof AutenticadaAuditoriaRoute
  '/importacion': typeof AutenticadaImportacionRoute
  '/personas': typeof AutenticadaPersonasRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/proyecto/$proyectoId': typeof AutenticadaProyectoProyectoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_autenticada': typeof AutenticadaRouteWithChildren
  '/login': typeof LoginRoute
  '/_autenticada/app': typeof AutenticadaAppRoute
  '/_autenticada/auditoria': typeof AutenticadaAuditoriaRoute
  '/_autenticada/importacion': typeof AutenticadaImportacionRoute
  '/_autenticada/personas': typeof AutenticadaPersonasRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/_autenticada/proyecto/$proyectoId': typeof AutenticadaProyectoProyectoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/auditoria'
    | '/importacion'
    | '/personas'
    | '/invitacion/$token'
    | '/proyecto/$proyectoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/auditoria'
    | '/importacion'
    | '/personas'
    | '/invitacion/$token'
    | '/proyecto/$proyectoId'
  id:
    | '__root__'
    | '/'
    | '/_autenticada'
    | '/login'
    | '/_autenticada/app'
    | '/_autenticada/auditoria'
    | '/_autenticada/importacion'
    | '/_autenticada/personas'
    | '/invitacion/$token'
    | '/_autenticada/proyecto/$proyectoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutenticadaRoute: typeof AutenticadaRouteWithChildren
  LoginRoute: typeof LoginRoute
  InvitacionTokenRoute: typeof InvitacionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticada': {
      id: '/_autenticada'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AutenticadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticada/app': {
      id: '/_autenticada/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AutenticadaAppRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/auditoria': {
      id: '/_autenticada/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AutenticadaAuditoriaRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/importacion': {
      id: '/_autenticada/importacion'
      path: '/importacion'
      fullPath: '/importacion'
      preLoaderRoute: typeof AutenticadaImportacionRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/_autenticada/personas': {
      id: '/_autenticada/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AutenticadaPersonasRouteImport
      parentRoute: typeof AutenticadaRoute
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticada/proyecto/$proyectoId': {
      id: '/_autenticada/proyecto/$proyectoId'
      path: '/proyecto/$proyectoId'
      fullPath: '/proyecto/$proyectoId'
      preLoaderRoute: typeof AutenticadaProyectoProyectoIdRouteImport
      parentRoute: typeof AutenticadaRoute
    }
  }
}

interface AutenticadaRouteChildren {
  AutenticadaAppRoute: typeof AutenticadaAppRoute
  AutenticadaAuditoriaRoute: typeof AutenticadaAuditoriaRoute
  AutenticadaImportacionRoute: typeof AutenticadaImportacionRoute
  AutenticadaPersonasRoute: typeof AutenticadaPersonasRoute
  AutenticadaProyectoProyectoIdRoute: typeof AutenticadaProyectoProyectoIdRoute
}

const AutenticadaRouteChildren: AutenticadaRouteChildren = {
  AutenticadaAppRoute: AutenticadaAppRoute,
  AutenticadaAuditoriaRoute: AutenticadaAuditoriaRoute,
  AutenticadaImportacionRoute: AutenticadaImportacionRoute,
  AutenticadaPersonasRoute: AutenticadaPersonasRoute,
  AutenticadaProyectoProyectoIdRoute: AutenticadaProyectoProyectoIdRoute,
}

const AutenticadaRouteWithChildren = AutenticadaRoute._addFileChildren(
  AutenticadaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutenticadaRoute: AutenticadaRouteWithChildren,
  LoginRoute: LoginRoute,
  InvitacionTokenRoute: InvitacionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
